"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "@/lib/supabase-browser";
import CobrancaForm from "./cobranca-form";
import { Plus, Search, ExternalLink } from "lucide-react";
function brl(n:number){return (n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
const C:any={pendente:"bg-amber-500/15 text-amber-500",pago:"bg-recover-500/15 text-recover-400",vencido:"bg-danger-500/15 text-danger-500",cancelado:"bg-white/10 text-ink-500",negociando:"bg-navy-600 text-ink-300"};
export default function Cobrancas(){
  const router=useRouter();const sb=supabaseBrowser();const [empresaId,setEmpresaId]=useState<string|null>(null);const [rows,setRows]=useState<any[]>([]);const [busca,setBusca]=useState("");const [filtro,setFiltro]=useState("todos");const [form,setForm]=useState(false);const [c,setC]=useState(true);
  async function carregar(){const {data:{user}}=await sb.auth.getUser();if(!user){router.push("/login");return;}const {data:u}=await sb.from("usuarios").select("empresa_id").eq("id",user.id).maybeSingle();if(!u){router.push("/onboarding");return;}setEmpresaId(u.empresa_id);const {data}=await sb.from("cobrancas").select("*, clientes(nome)").order("vencimento_date",{ascending:false}).limit(500);setRows(data??[]);setC(false);}
  useEffect(()=>{carregar();},[]);
  const fl=rows.filter(r=>{if(filtro!=="todos"&&r.status!==filtro)return false;if(!busca)return true;const q=busca.toLowerCase();return (r.numero||"").toLowerCase().includes(q)||(r.descricao||"").toLowerCase().includes(q)||(r.clientes?.nome||"").toLowerCase().includes(q);});
  const aReceber=rows.filter(r=>r.status==="pendente").reduce((s,r)=>s+(r.valor||0),0);const vencido=rows.filter(r=>r.status==="vencido").reduce((s,r)=>s+(r.valor||0),0);const recebido=rows.filter(r=>r.status==="pago").reduce((s,r)=>s+(r.valor||0),0);
  return (<div className="mx-auto max-w-6xl px-6 py-8"><div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold text-ink-100">Cobranças</h1><p className="mt-1 text-ink-300">Gerencie cobranças e pagamentos.</p></div><button onClick={()=>setForm(true)} className="inline-flex items-center gap-2 rounded-lg bg-recover-500 px-4 py-2.5 font-medium text-navy-900 hover:bg-recover-400"><Plus size={18}/> Nova cobrança</button></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-4">{[["Total",String(rows.length)],["A receber",brl(aReceber)],["Vencido",brl(vencido)],["Recebido",brl(recebido)]].map(([l,v])=>(<div key={l} className="rounded-xl border border-white/10 bg-navy-800/60 p-4"><div className="text-xs uppercase tracking-widest text-ink-500">{l}</div><div className="mt-2 font-display text-xl font-bold text-ink-100">{v}</div></div>))}</div>
    <div className="mt-6 flex flex-wrap items-center gap-3"><div className="relative flex-1 min-w-[240px]"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-500"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar…" className="w-full rounded-lg border border-white/10 bg-navy-900 py-2.5 pl-9 pr-3 text-ink-100 outline-none focus:border-recover-500"/></div><select value={filtro} onChange={e=>setFiltro(e.target.value)} className="rounded-lg border border-white/10 bg-navy-900 px-3 py-2.5 text-ink-100 outline-none"><option value="todos">Todos</option><option value="pendente">Pendente</option><option value="pago">Pago</option><option value="vencido">Vencido</option></select></div>
    <div className="mt-4 overflow-hidden rounded-2xl border border-white/10"><table className="w-full text-sm"><thead className="bg-white/[0.04] text-left text-ink-500"><tr><th className="px-4 py-3">Número / Cliente</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Vencimento</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Pagar</th></tr></thead>
      <tbody>{c&&<tr><td colSpan={5} className="px-4 py-8 text-center text-ink-500">Carregando…</td></tr>}{!c&&fl.length===0&&<tr><td colSpan={5} className="px-4 py-10 text-center text-ink-500">Nenhuma cobrança.</td></tr>}
      {fl.map(r=>(<tr key={r.id} className="border-t border-white/5 hover:bg-white/[0.02]"><td className="px-4 py-3"><div className="text-ink-100">{r.clientes?.nome||"—"}</div><div className="text-xs text-ink-500">{r.numero}{r.descricao?` · ${r.descricao}`:""}</div></td><td className="px-4 py-3 text-right text-ink-100">{brl(r.valor)}</td><td className="px-4 py-3 text-ink-300">{r.vencimento_date?new Date(r.vencimento_date+"T00:00:00").toLocaleDateString("pt-BR"):"—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-0.5 text-xs ${C[r.status]||""}`}>{r.status}</span></td><td className="px-4 py-3"><a href={`/pagar/${r.token_publico}`} target="_blank" className="inline-flex items-center gap-1 text-recover-400 hover:underline">link <ExternalLink size={13}/></a></td></tr>))}</tbody></table></div>
    {form&&empresaId&&<CobrancaForm empresaId={empresaId} onClose={()=>setForm(false)} onSaved={()=>{setForm(false);carregar();}}/>}</div>);
}
