"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "@/lib/supabase-browser";
import { Plus, Trash2, Check, X } from "lucide-react";
function brl(n:number){return (n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
export default function ContasPagar(){
  const router=useRouter();const sb=supabaseBrowser();const [empresaId,setEmpresaId]=useState<string|null>(null);const [rows,setRows]=useState<any[]>([]);const [form,setForm]=useState<any|undefined>(undefined);
  async function carregar(){const {data:{user}}=await sb.auth.getUser();if(!user){router.push("/login");return;}const {data:u}=await sb.from("usuarios").select("empresa_id").eq("id",user.id).maybeSingle();if(!u){router.push("/onboarding");return;}setEmpresaId(u.empresa_id);const {data}=await sb.from("contas_a_pagar").select("*").order("vencimento_date");setRows(data??[]);}
  useEffect(()=>{carregar();},[]);
  async function salvar(){if(!empresaId||!form?.descricao)return;const {error}=await sb.from("contas_a_pagar").insert({empresa_id:empresaId,descricao:form.descricao,fornecedor:form.fornecedor||null,categoria:form.categoria||null,valor:Number(form.valor)||0,vencimento_date:form.vencimento_date||null,status:"pendente"});if(!error){setForm(undefined);carregar();}}
  async function pagar(id:string){await sb.from("contas_a_pagar").update({status:"pago"}).eq("id",id);carregar();}
  async function excluir(id:string){await sb.from("contas_a_pagar").delete().eq("id",id);carregar();}
  const total=rows.filter(r=>r.status!=="pago").reduce((s,r)=>s+(r.valor||0),0);
  const I="mt-1 w-full rounded-lg border border-white/10 bg-navy-900 px-3 py-2.5 text-ink-100 outline-none focus:border-recover-500";const L="block text-xs text-ink-500";
  return (<div className="mx-auto max-w-5xl px-6 py-8"><div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold text-ink-100">Contas a Pagar</h1><p className="mt-1 text-ink-300">A pagar: <b className="text-amber-500">{brl(total)}</b></p></div><button onClick={()=>setForm({})} className="inline-flex items-center gap-2 rounded-lg bg-recover-500 px-4 py-2.5 font-medium text-navy-900 hover:bg-recover-400"><Plus size={18}/> Nova conta</button></div>
    <div className="mt-6 overflow-hidden rounded-2xl border border-white/10"><table className="w-full text-sm"><thead className="bg-white/[0.04] text-left text-ink-500"><tr><th className="px-4 py-3">Descrição</th><th className="px-4 py-3">Fornecedor</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Vencimento</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead>
      <tbody>{rows.length===0&&<tr><td colSpan={6} className="px-4 py-10 text-center text-ink-500">Nenhuma conta.</td></tr>}{rows.map(r=>(<tr key={r.id} className="border-t border-white/5"><td className="px-4 py-3 text-ink-100">{r.descricao}</td><td className="px-4 py-3 text-ink-300">{r.fornecedor||"—"}</td><td className="px-4 py-3 text-right text-ink-100">{brl(r.valor)}</td><td className="px-4 py-3 text-ink-300">{r.vencimento_date?new Date(r.vencimento_date+"T00:00:00").toLocaleDateString("pt-BR"):"—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-0.5 text-xs ${r.status==="pago"?"bg-recover-500/15 text-recover-400":"bg-amber-500/15 text-amber-500"}`}>{r.status}</span></td><td className="px-4 py-3"><div className="flex justify-end gap-2">{r.status!=="pago"&&<button onClick={()=>pagar(r.id)} className="text-ink-500 hover:text-recover-400" title="Marcar pago"><Check size={16}/></button>}<button onClick={()=>excluir(r.id)} className="text-ink-500 hover:text-danger-500"><Trash2 size={16}/></button></div></td></tr>))}</tbody></table></div>
    {form!==undefined&&(<div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/60 p-4"><div className="my-8 w-full max-w-lg rounded-2xl border border-white/10 bg-navy-800 p-6"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold text-ink-100">Nova conta</h2><button onClick={()=>setForm(undefined)} className="text-ink-500 hover:text-ink-100"><X size={20}/></button></div>
      <div className="mt-5 grid gap-4"><div><label className={L}>Descrição *</label><input className={I} value={form.descricao||""} onChange={e=>setForm({...form,descricao:e.target.value})}/></div><div className="grid grid-cols-2 gap-4"><div><label className={L}>Fornecedor</label><input className={I} value={form.fornecedor||""} onChange={e=>setForm({...form,fornecedor:e.target.value})}/></div><div><label className={L}>Categoria</label><input className={I} value={form.categoria||""} onChange={e=>setForm({...form,categoria:e.target.value})}/></div></div><div className="grid grid-cols-2 gap-4"><div><label className={L}>Valor (R$)</label><input className={I} value={form.valor||""} onChange={e=>setForm({...form,valor:e.target.value})}/></div><div><label className={L}>Vencimento</label><input type="date" className={I} value={form.vencimento_date||""} onChange={e=>setForm({...form,vencimento_date:e.target.value})}/></div></div><div className="flex justify-end gap-2"><button onClick={()=>setForm(undefined)} className="rounded-lg border border-white/15 px-4 py-2.5 text-sm text-ink-100 hover:bg-white/5">Cancelar</button><button onClick={salvar} className="rounded-lg bg-recover-500 px-6 py-2.5 font-medium text-navy-900">Salvar</button></div></div></div></div>)}
  </div>);
}
