"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "@/lib/supabase-browser";
import { Plus, Check, X } from "lucide-react";
function brl(n:number){return (n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
const C:any={proposta:"bg-amber-500/15 text-amber-500",aprovada:"bg-recover-500/15 text-recover-400",recusada:"bg-danger-500/15 text-danger-500",quitada:"bg-navy-600 text-ink-300"};
export default function Negociacoes(){
  const router=useRouter();const sb=supabaseBrowser();const [empresaId,setEmpresaId]=useState<string|null>(null);const [rows,setRows]=useState<any[]>([]);const [clientes,setClientes]=useState<any[]>([]);const [form,setForm]=useState<any|undefined>(undefined);
  async function carregar(){const {data:{user}}=await sb.auth.getUser();if(!user){router.push("/login");return;}const {data:u}=await sb.from("usuarios").select("empresa_id").eq("id",user.id).maybeSingle();if(!u){router.push("/onboarding");return;}setEmpresaId(u.empresa_id);
    const {data}=await sb.from("negociacoes").select("*, clientes(nome)").order("created_at",{ascending:false});setRows(data??[]);
    const {data:cl}=await sb.from("clientes").select("id,nome").order("nome");setClientes(cl??[]);}
  useEffect(()=>{carregar();},[]);
  async function salvar(){if(!empresaId||!form?.cliente_id)return;const orig=Number(form.valor_original)||0,neg=Number(form.valor_negociado)||0;const desc=orig>0?Math.round((1-neg/orig)*1000)/10:0;
    const {error}=await sb.from("negociacoes").insert({empresa_id:empresaId,cliente_id:form.cliente_id,valor_original:orig,valor_negociado:neg,desconto_percent:desc,parcelas:Number(form.parcelas)||1,status:"proposta",observacoes:form.observacoes||null});if(!error){setForm(undefined);carregar();}}
  async function status(id:string,s:string){await sb.from("negociacoes").update({status:s}).eq("id",id);carregar();}
  const I="mt-1 w-full rounded-lg border border-white/10 bg-navy-900 px-3 py-2.5 text-ink-100 outline-none focus:border-recover-500";const L="block text-xs text-ink-500";
  return (<div className="mx-auto max-w-5xl px-6 py-8"><div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold text-ink-100">Negociações</h1><p className="mt-1 text-ink-300">Propostas de acordo.</p></div><button onClick={()=>setForm({parcelas:1})} className="inline-flex items-center gap-2 rounded-lg bg-recover-500 px-4 py-2.5 font-medium text-navy-900 hover:bg-recover-400"><Plus size={18}/> Nova negociação</button></div>
    <div className="mt-6 overflow-hidden rounded-2xl border border-white/10"><table className="w-full text-sm"><thead className="bg-white/[0.04] text-left text-ink-500"><tr><th className="px-4 py-3">Cliente</th><th className="px-4 py-3 text-right">Original</th><th className="px-4 py-3 text-right">Negociado</th><th className="px-4 py-3">Desc.</th><th className="px-4 py-3">Parc.</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead>
      <tbody>{rows.length===0&&<tr><td colSpan={7} className="px-4 py-10 text-center text-ink-500">Nenhuma negociação.</td></tr>}{rows.map(r=>(<tr key={r.id} className="border-t border-white/5"><td className="px-4 py-3 text-ink-100">{r.clientes?.nome||"—"}</td><td className="px-4 py-3 text-right text-ink-300">{brl(r.valor_original)}</td><td className="px-4 py-3 text-right text-recover-400">{brl(r.valor_negociado)}</td><td className="px-4 py-3 text-ink-300">{r.desconto_percent||0}%</td><td className="px-4 py-3 text-ink-300">{r.parcelas}x</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-0.5 text-xs ${C[r.status]||""}`}>{r.status}</span></td><td className="px-4 py-3">{r.status==="proposta"&&<div className="flex justify-end gap-2"><button onClick={()=>status(r.id,"aprovada")} className="text-ink-500 hover:text-recover-400"><Check size={16}/></button><button onClick={()=>status(r.id,"recusada")} className="text-ink-500 hover:text-danger-500"><X size={16}/></button></div>}</td></tr>))}</tbody></table></div>
    {form!==undefined&&(<div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/60 p-4"><div className="my-8 w-full max-w-lg rounded-2xl border border-white/10 bg-navy-800 p-6"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold text-ink-100">Nova negociação</h2><button onClick={()=>setForm(undefined)} className="text-ink-500 hover:text-ink-100"><X size={20}/></button></div>
      <div className="mt-5 grid gap-4"><div><label className={L}>Cliente *</label><select className={I} value={form.cliente_id||""} onChange={e=>setForm({...form,cliente_id:e.target.value})}><option value="">Selecione…</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></div><div className="grid grid-cols-3 gap-4"><div><label className={L}>Valor original</label><input className={I} value={form.valor_original||""} onChange={e=>setForm({...form,valor_original:e.target.value})}/></div><div><label className={L}>Valor negociado</label><input className={I} value={form.valor_negociado||""} onChange={e=>setForm({...form,valor_negociado:e.target.value})}/></div><div><label className={L}>Parcelas</label><input className={I} value={form.parcelas||1} onChange={e=>setForm({...form,parcelas:e.target.value})}/></div></div><div><label className={L}>Observações</label><textarea className={I} rows={2} value={form.observacoes||""} onChange={e=>setForm({...form,observacoes:e.target.value})}/></div><div className="flex justify-end gap-2"><button onClick={()=>setForm(undefined)} className="rounded-lg border border-white/15 px-4 py-2.5 text-sm text-ink-100 hover:bg-white/5">Cancelar</button><button onClick={salvar} className="rounded-lg bg-recover-500 px-6 py-2.5 font-medium text-navy-900">Salvar</button></div></div></div></div>)}
  </div>);
}
