"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "@/lib/supabase-browser";
import { Plus, RefreshCw, X } from "lucide-react";
function brl(n:number){return (n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
export default function FluxoCaixa(){
  const router=useRouter();const sb=supabaseBrowser();const [empresaId,setEmpresaId]=useState<string|null>(null);const [rows,setRows]=useState<any[]>([]);const [form,setForm]=useState<any|undefined>(undefined);const [sinc,setSinc]=useState(false);const [msg,setMsg]=useState<string|null>(null);
  async function carregar(){const {data:{user}}=await sb.auth.getUser();if(!user){router.push("/login");return;}const {data:u}=await sb.from("usuarios").select("empresa_id").eq("id",user.id).maybeSingle();if(!u){router.push("/onboarding");return;}setEmpresaId(u.empresa_id);const {data}=await sb.from("movimentacoes").select("*").order("data_movimentacao",{ascending:false}).limit(500);setRows(data??[]);}
  useEffect(()=>{carregar();},[]);
  async function salvar(){if(!empresaId||!form?.descricao)return;const {error}=await sb.from("movimentacoes").insert({empresa_id:empresaId,tipo:form.tipo||"despesa",categoria:form.categoria||null,descricao:form.descricao,valor:Number(form.valor)||0,data_movimentacao:form.data_movimentacao||new Date().toISOString().slice(0,10)});if(!error){setForm(undefined);carregar();}}
  async function sincronizar(){setSinc(true);setMsg(null);try{const r=await fetch("/api/fluxo/sincronizar",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d?.erro||"falha");setMsg(`${d.criadas} receitas sincronizadas.`);carregar();}catch(e:any){setMsg("Erro: "+e.message);}finally{setSinc(false);}}
  const receitas=rows.filter(r=>r.tipo==="receita").reduce((s,r)=>s+(r.valor||0),0);const despesas=rows.filter(r=>r.tipo==="despesa").reduce((s,r)=>s+(r.valor||0),0);const saldo=receitas-despesas;
  const I="mt-1 w-full rounded-lg border border-white/10 bg-navy-900 px-3 py-2.5 text-ink-100 outline-none focus:border-recover-500";const L="block text-xs text-ink-500";
  return (<div className="mx-auto max-w-5xl px-6 py-8"><div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold text-ink-100">Fluxo de Caixa</h1><p className="mt-1 text-ink-300">Receitas e despesas.</p></div><div className="flex gap-2"><button onClick={sincronizar} disabled={sinc} className="inline-flex items-center gap-2 rounded-lg border border-white/15 px-4 py-2.5 text-sm text-ink-100 hover:bg-white/5 disabled:opacity-50"><RefreshCw size={16} className={sinc?"animate-spin":""}/> Sincronizar receitas</button><button onClick={()=>setForm({tipo:"despesa"})} className="inline-flex items-center gap-2 rounded-lg bg-recover-500 px-4 py-2.5 font-medium text-navy-900 hover:bg-recover-400"><Plus size={18}/> Lançar</button></div></div>
    {msg&&<p className="mt-3 text-sm text-recover-400">{msg}</p>}
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-navy-800/60 p-4"><div className="text-xs uppercase tracking-widest text-ink-500">Receitas</div><div className="mt-2 font-display text-xl font-bold text-recover-400">{brl(receitas)}</div></div><div className="rounded-xl border border-white/10 bg-navy-800/60 p-4"><div className="text-xs uppercase tracking-widest text-ink-500">Despesas</div><div className="mt-2 font-display text-xl font-bold text-danger-500">{brl(despesas)}</div></div><div className="rounded-xl border border-white/10 bg-navy-800/60 p-4"><div className="text-xs uppercase tracking-widest text-ink-500">Saldo</div><div className={`mt-2 font-display text-xl font-bold ${saldo>=0?"text-ink-100":"text-danger-500"}`}>{brl(saldo)}</div></div></div>
    <div className="mt-6 overflow-hidden rounded-2xl border border-white/10"><table className="w-full text-sm"><thead className="bg-white/[0.04] text-left text-ink-500"><tr><th className="px-4 py-3">Descrição</th><th className="px-4 py-3">Categoria</th><th className="px-4 py-3">Data</th><th className="px-4 py-3 text-right">Valor</th></tr></thead>
      <tbody>{rows.length===0&&<tr><td colSpan={4} className="px-4 py-10 text-center text-ink-500">Nenhum lançamento.</td></tr>}{rows.map(r=>(<tr key={r.id} className="border-t border-white/5"><td className="px-4 py-3 text-ink-100">{r.descricao}</td><td className="px-4 py-3 text-ink-300">{r.categoria||"—"}</td><td className="px-4 py-3 text-ink-500">{r.data_movimentacao?new Date(r.data_movimentacao+"T00:00:00").toLocaleDateString("pt-BR"):"—"}</td><td className={`px-4 py-3 text-right ${r.tipo==="receita"?"text-recover-400":"text-danger-500"}`}>{r.tipo==="receita"?"+":"−"}{brl(r.valor)}</td></tr>))}</tbody></table></div>
    {form!==undefined&&(<div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/60 p-4"><div className="my-8 w-full max-w-lg rounded-2xl border border-white/10 bg-navy-800 p-6"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold text-ink-100">Novo lançamento</h2><button onClick={()=>setForm(undefined)} className="text-ink-500 hover:text-ink-100"><X size={20}/></button></div>
      <div className="mt-5 grid gap-4"><div className="grid grid-cols-2 gap-4"><div><label className={L}>Tipo</label><select className={I} value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option value="despesa">Despesa</option><option value="receita">Receita</option></select></div><div><label className={L}>Categoria</label><input className={I} value={form.categoria||""} onChange={e=>setForm({...form,categoria:e.target.value})}/></div></div><div><label className={L}>Descrição *</label><input className={I} value={form.descricao||""} onChange={e=>setForm({...form,descricao:e.target.value})}/></div><div className="grid grid-cols-2 gap-4"><div><label className={L}>Valor (R$)</label><input className={I} value={form.valor||""} onChange={e=>setForm({...form,valor:e.target.value})}/></div><div><label className={L}>Data</label><input type="date" className={I} value={form.data_movimentacao||""} onChange={e=>setForm({...form,data_movimentacao:e.target.value})}/></div></div><div className="flex justify-end gap-2"><button onClick={()=>setForm(undefined)} className="rounded-lg border border-white/15 px-4 py-2.5 text-sm text-ink-100 hover:bg-white/5">Cancelar</button><button onClick={salvar} className="rounded-lg bg-recover-500 px-6 py-2.5 font-medium text-navy-900">Salvar</button></div></div></div></div>)}
  </div>);
}
