"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "@/lib/supabase-browser";
import { Plus, Trash2, X } from "lucide-react";
const CANAIS=["whatsapp","email","sms"];
export default function Campanhas(){
  const router=useRouter();const sb=supabaseBrowser();const [empresaId,setEmpresaId]=useState<string|null>(null);const [rows,setRows]=useState<any[]>([]);const [form,setForm]=useState<any|undefined>(undefined);
  async function carregar(){const {data:{user}}=await sb.auth.getUser();if(!user){router.push("/login");return;}const {data:u}=await sb.from("usuarios").select("empresa_id").eq("id",user.id).maybeSingle();if(!u){router.push("/onboarding");return;}setEmpresaId(u.empresa_id);const {data}=await sb.from("campanhas_cobranca").select("*").order("created_at",{ascending:false});setRows(data??[]);}
  useEffect(()=>{carregar();},[]);
  async function salvar(){if(!empresaId||!form?.nome)return;const {error}=await sb.from("campanhas_cobranca").insert({empresa_id:empresaId,nome:form.nome,descricao:form.descricao||null,tom:form.tom||"formal",canais:form.canais||[],status:"ativa"});if(!error){setForm(undefined);carregar();}}
  async function excluir(id:string){await sb.from("campanhas_cobranca").delete().eq("id",id);carregar();}
  function toggle(c:string){const arr=form.canais||[];setForm({...form,canais:arr.includes(c)?arr.filter((x:string)=>x!==c):[...arr,c]});}
  const I="mt-1 w-full rounded-lg border border-white/10 bg-navy-900 px-3 py-2.5 text-ink-100 outline-none focus:border-recover-500";const L="block text-xs text-ink-500";
  return (<div className="mx-auto max-w-5xl px-6 py-8"><div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold text-ink-100">Campanhas</h1><p className="mt-1 text-ink-300">Estratégias de cobrança por tom e canal.</p></div><button onClick={()=>setForm({tom:"formal",canais:["whatsapp"]})} className="inline-flex items-center gap-2 rounded-lg bg-recover-500 px-4 py-2.5 font-medium text-navy-900 hover:bg-recover-400"><Plus size={18}/> Nova campanha</button></div>
    <div className="mt-6 grid gap-3 md:grid-cols-2">{rows.length===0&&<p className="text-ink-500">Nenhuma campanha.</p>}{rows.map(r=>(<div key={r.id} className="rounded-xl border border-white/10 bg-navy-800/60 p-5"><div className="flex items-start justify-between"><div><div className="font-display font-medium text-ink-100">{r.nome}</div><div className="mt-1 text-xs text-ink-500">Tom: {r.tom} · {(r.canais||[]).join(", ")||"—"}</div>{r.descricao&&<p className="mt-2 text-sm text-ink-300">{r.descricao}</p>}</div><button onClick={()=>excluir(r.id)} className="text-ink-500 hover:text-danger-500"><Trash2 size={16}/></button></div><span className="mt-3 inline-block rounded-full bg-recover-500/15 px-2 py-0.5 text-xs text-recover-400">{r.status}</span></div>))}</div>
    {form!==undefined&&(<div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/60 p-4"><div className="my-8 w-full max-w-lg rounded-2xl border border-white/10 bg-navy-800 p-6"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold text-ink-100">Nova campanha</h2><button onClick={()=>setForm(undefined)} className="text-ink-500 hover:text-ink-100"><X size={20}/></button></div>
      <div className="mt-5 grid gap-4"><div><label className={L}>Nome *</label><input className={I} value={form.nome||""} onChange={e=>setForm({...form,nome:e.target.value})}/></div><div><label className={L}>Descrição</label><textarea className={I} rows={2} value={form.descricao||""} onChange={e=>setForm({...form,descricao:e.target.value})}/></div><div><label className={L}>Tom</label><select className={I} value={form.tom} onChange={e=>setForm({...form,tom:e.target.value})}><option value="amigavel">Amigável</option><option value="formal">Formal</option><option value="firme">Firme</option><option value="urgente">Urgente</option></select></div><div><label className={L}>Canais</label><div className="mt-2 flex gap-2">{CANAIS.map(c=><button key={c} onClick={()=>toggle(c)} className={`rounded-lg border px-3 py-1.5 text-sm capitalize ${(form.canais||[]).includes(c)?"border-recover-500 bg-recover-500/15 text-recover-400":"border-white/10 text-ink-300"}`}>{c}</button>)}</div></div><div className="flex justify-end gap-2"><button onClick={()=>setForm(undefined)} className="rounded-lg border border-white/15 px-4 py-2.5 text-sm text-ink-100 hover:bg-white/5">Cancelar</button><button onClick={salvar} className="rounded-lg bg-recover-500 px-6 py-2.5 font-medium text-navy-900">Salvar</button></div></div></div></div>)}
  </div>);
}
